name: flutter_credential_picker
description: Credential picker for Google Service
version: 0.0.1
homepage: https://github.com/printeastwoodcz/flutter_credential_plugin
repository: https://github.com/printeastwoodcz/flutter_credential_plugin
issue_tracker: https://github.com/printeastwoodcz/flutter_credential_plugin/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: cz.printeastwood.flutter_credential_picker
        pluginClass: FlutterCredentialPickerPlugin
      ios:
        pluginClass: FlutterCredentialPickerPlugin
